vich_uploader:
    db_driver: orm

    mappings:
        crafts:
            uri_prefix: /images/crafts
            upload_destination: '%kernel.project_dir%/public/images/crafts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        giveaways:
            uri_prefix: /images/giveaways
            upload_destination: '%kernel.project_dir%/public/images/giveaways'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
