###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
  version: "3.1"

  services:

    db:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      container_name: app-mysql
      working_dir: /application
      volumes:
        - .:/application
        - data-volume:/var/lib/db
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=symfony
        - MYSQL_USER=symfony
        - MYSQL_PASSWORD=symfony

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: pma
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      restart: always
      ports:
        - 8183:80 

    webserver:
      image: nginx:alpine
      container_name: application-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: application-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    mercure:
      image: dunglas/mercure
      ports:
          - 3000:80
      environment:
          - JWT_KEY=pookie
          - DEMO=1
          - ALLOW_ANONYMOUS=1
          - CORS_ALLOWED_ORIGINS=*
          - PUBLISH_ALLOWED_ORIGINS=http://localhost

  volumes:
    data-volume:
      